language: go

go_import_path: github.com/rohitsubedi/levenshtein

before_install:
  - export GO111MODULE=on

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - tip

install:
  - go get github.com/stretchr/testify@v1.6.1
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - make check
